version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11.3
    steps:
      - add_ssh_keys:
          fingerprints:
            # https://circleci.com/gh/pingcap/pingcap.github.io/edit#checkout
            - '1b:b6:ef:e0:fb:85:6d:8f:78:87:a6:ce:1f:34:ec:66'
            # Use in scripts/push-gh-pages.sh
            - '6a:a6:ac:e8:9e:ee:7d:ef:18:92:94:0b:b0:2c:34:82'

      - checkout

      # Dependencies required for deploy
      # python3-pip for awscli
      - run: sudo apt update && sudo apt install rsync python-bs4 python3-pip -y

      # Download and cache dependencies and submodules
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # Fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          command: npm run build
          no_output_timeout: 20m

      - deploy:
          name: 'Publish Website Could LA_1_HOST'
          command : |
            if [ "${CIRCLE_BRANCH}" == "src" ]
            then
              ssh-keyscan "${DEPLOY_UCLOUD_LA_1_HOST}" >> ~/.ssh/known_hosts 2>/dev/null;
              rsync -avz --delete dist/ "${DEPLOY_UCLOUD_USER}@${DEPLOY_UCLOUD_LA_1_HOST}:${DEPLOY_UCLOUD_PATH}";
              curl "http://www.google.com/ping?sitemap=https://pingcap.com.cn/sitemap.xml"
            fi

  build-and-deploy-XC:
    docker:
      - image: circleci/node:8.11.3
    steps:
      - add_ssh_keys:
          fingerprints:
            - 'f7:0b:c3:e6:35:00:70:26:40:66:3f:e3:ca:54:33:fa'
            - '96:82:25:e6:7e:1f:4c:00:33:34:76:0a:e0:b4:ee:dd'
      - checkout
      # Dependencies required for deploy
      # python3-pip for awscli
      - run: sudo apt update && sudo apt install rsync python3 python-bs4 python3-pip -y
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # Fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: npm install
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: build
          command: npm run build
          no_output_timeout: 20m
      - run:
          name: deploy
          command: |
            ssh-keyscan "${XC_HOST}" >> ~/.ssh/known_hosts 2>/dev/null;
            rsync -avz --progress --delete dist/ ${XC_USER}@${XC_HOST}:${XC_PATH}
          no_output_timeout: 5m

  preview:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - run: curl -X POST -d {} https://api.netlify.com/build_hooks/5e71c8a620f3419c2fea69cc
workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - src
      - preview:
          filters:
            branches:
              only:
                - preview
  deploy-XC:
    jobs:
      - build-and-deploy-XC:
          filters:
            branches:
              only:
                - XC_Web
